siteTitle = "David A. Lareo"
siteDescr = "Sitio web personal: artículos, proyectos y material de autobombo"
siteAuthor = "David A. Lareo"

siteTelegramUrl = "https://telegram.me/dalareo"
siteTwitterUrl = "https://twitter.com/dalareo"
siteGithubUrl = "https://github.com/dalareo"
siteEmailUrl = "mailto:dalareo@gmail.com"
siteRssUrl = "#"
# siteVkUrl = "#"

googleAnalyticsId = "UA-51798222-3"

linkPrefix = ""
